Create Database DTM;
use DTM;

CREATE TABLE Car (
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(16),
	PRICE DECIMAL,
	BRAND VARCHAR(32),
	DATE_CREATED DATE,
	MODEL VARCHAR(32),
	MANUFACTURER VARCHAR(32),
	DESCRIPTION VARCHAR(150),
	SEAT_CAPACITY INTEGER,
	FUEL_TYPE INTEGER,
	MILEAGE INTEGER,
	TRANMISSION_TYPE INTEGER
);

CREATE TABLE MOTORBIKE (
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(16),
	PRICE DECIMAL,
	BRAND VARCHAR(32),
	DATE_CREATED DATE,
	MODEL VARCHAR(32),
	MANUFACTURER VARCHAR(32),
	DESCRIPTION VARCHAR(150),
	
	FUEL_TYPE INTEGER,
	NUMBER_OF_ENGINE INTEGER,
	TRANMISSION_TYPE INTEGER
);

CREATE TABLE BIKE (
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(16),
	PRICE DECIMAL,
	BRAND VARCHAR(32),
	DATE_CREATED DATE,
	MODEL VARCHAR(32),
	MANUFACTURER VARCHAR(32),
	DESCRIPTION VARCHAR(150),
	
	TYPE INTEGER
);

CREATE TABLE CUSTOMER (
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(16),
	PHONE VARCHAR(16),
	EMAIL VARCHAR(32),
	BIRTHDATE DATE,
	PASSWORD VARCHAR(50),
	TYPE INT,
	HOBBIES VARCHAR(150),
	MARRIAGE_STATUS INT
);

CREATE TABLE DEALER (
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(16),
	PHONE VARCHAR(16),
	EMAIL VARCHAR(32),
	BIRTHDATE DATE,
	PASSWORD VARCHAR(50),
	TITLE VARCHAR(15),
	TYPE INT
);

CREATE TABLE ORDER_ (
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	AMOUNT DECIMAL,
	ORDER_DATE DATE,
	CUSTOMER_ID INTEGER NOT NULL
);


CREATE TABLE ORDER_TRANSPORT (
	ORDER_ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TRANSPORT_ID INTEGER,
	PRICE DECIMAL
);

