CREATE TABLE APP.Car (
	ID INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(16),
	PRICE DECIMAL,
	BRAND VARCHAR(32),
	DATE_CREATED DATE,
	MODEL VARCHAR(32),
	MANUFACTURER VARCHAR(32),
	DESCRIPTION VARCHAR(150),
	SEAT_CAPACITY INTEGER,
	FUEL_TYPE INTEGER,
	MILEAGE INTEGER,
	TRANMISSION_TYPE INTEGER
);

CREATE TABLE APP.MOTORBIKE (
	ID INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(16),
	PRICE DECIMAL,
	BRAND VARCHAR(32),
	DATE_CREATED DATE,
	MODEL VARCHAR(32),
	MANUFACTURER VARCHAR(32),
	DESCRIPTION VARCHAR(150),
	
	FUEL_TYPE INTEGER,
	NUMBER_OF_ENGINE INTEGER,
	TRANMISSION_TYPE INTEGER
);

CREATE TABLE APP.BIKE (
	ID INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(16),
	PRICE DECIMAL,
	BRAND VARCHAR(32),
	DATE_CREATED DATE,
	MODEL VARCHAR(32),
	MANUFACTURER VARCHAR(32),
	DESCRIPTION VARCHAR(150),
	
	TYPE INTEGER
);

CREATE TABLE APP.CUSTOMER (
	ID INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(16),
	PHONE VARCHAR(16),
	EMAIL VARCHAR(32),
	BIRTHDATE DATE,
	PASSWORD VARCHAR(50),
	TYPE INT,
	HOBBIES VARCHAR(150),
	MARRIAGE_STATUS INT
);

CREATE TABLE APP.DEALER (
	ID INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(16),
	PHONE VARCHAR(16),
	EMAIL VARCHAR(32),
	BIRTHDATE DATE,
	PASSWORD VARCHAR(50),
	TITLE VARCHAR(15),
	TYPE INT
);

CREATE TABLE APP.ORDER_ (
	ID INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	AMOUNT DECIMAL,
	ORDER_DATE DATE,
	CUSTOMER_ID INTEGER NOT NULL
);


CREATE TABLE APP.ORDER_TRANSPORT (
	ORDER_ID INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	TRANSPORT_ID INTEGER,
	PRICE DECIMAL
);


SELECT * FROM "APP"."TBL_STUDENTS";